GET https://cse341-anita-test.onrender.com

//
###
GET http://localhost:8080/contacts
//
###
GET http://localhost:8080/contacts/6323565594c26c2157fcfd45
//
###
GET http://localhost:8080/contacts/6323565594c26c2157fcfd43
//
###
GET http://localhost:8080/contacts/6323565594c26c2157fcfd44

// Render
###
GET https://cse341-anita-pa2.onrender.com/contacts
//
###
GET https://cse341-anita-pa2.onrender.com/contacts/6323565594c26c2157fcfd45
//
###
GET https://cse341-anita-pa2.onrender.com/contacts/6323565594c26c2157fcfd43
//
###
GET https://cse341-anita-pa2.onrender.com/contacts/6323565594c26c2157fcfd44


###
POST https://cse341-anita-pa2.onrender.com/contacts HTTP/1.1
content-type: application/json 

{
    "firstName":"Christy",
    "lastName": "Ngozi",
    "email": "chngozi@yahoo.com",
    "favoriteColor": "Black",
    "birthday": "25/07/1989"
}

###
POST http://localhost:8080/contacts  HTTP/1.1
content-type: application/json 

{
    "firstName":"Dele",
    "lastName": "Adebisi",
    "email": "debus@gmail.com",
    "favoriteColor": "Green",
    "birthday": "20/02/1997"
}

###
PUT https://cse341-anita-pa2.onrender.com/contacts/632b2a9a1f776fedbcc34910 HTTP/1.1
content-type: application/json

{
    "firstName":"Christiana",
    "lastName": "Ngozi",
    "email": "cngozi@yahoo.com",
    "favoriteColor": "White",
    "birthday": "25/07/1989"
}

###
PUT http://localhost:8080/contacts/632b2a9a1f776fedbcc34910 HTTP/1.1
content-type: application/json

{
    "firstName":"Christiana",
    "lastName": "Ngozi",
    "email": "cngozi@yahoo.com",
    "favoriteColor": "Brown",
    "birthday": "25/07/1989"
}

###
DELETE https://cse341-anita-pa2.onrender.com/contacts/632b7c3f9726e771e69d289c HTTP/1.1
content-type: application/json

###
DELETE http://localhost:8080/contacts/632b6ca3f1ac97ba7cbaf145 HTTP/1.1
content-type: application/json